### ISSUE TITLE
Events no longer bubble

### ISSUE THREAD

**Issue by mwiencek** [rniemeyer/knockout-delegatedEvents#7]
Thanks for the awesome plugin, first of all. :)

In 8934ee1 events were made to never bubble, but I don't quite understand the reason. I noticed this because it breaks all of my widgets that rely on event bubbling.

Here's a very stripped-down example...

``` HTML
<body data-bind="delegatedHandler: 'keydown'">
  <div data-bind="with: dialog" data-keydown="keydownEvent">
    <div data-bind="with: autocomplete">
      <input data-keydown="keydownEvent">
      <div class="menu"></div>
    </div>
  </div>
</body>
```

The dialog has certain default keydown shortcuts. Pressing enter submits it and pressing escape cancels it. There's an autocomplete search inside the dialog that handles the same events. If the search menu is open, escape closes the menu (rather than the dialog), and pressing enter selects a menu item (rather than accepting the dialog).

Even if the menu is closed, `autocomplete.keydownEvent` is still executed, so post-8934ee1 the event no longer bubbles up to `dialog.keydownEvent`.

There's also some outside jQuery code that manually registers events on the document/body and handles various actions, and these don't see the event either.

Depending on why the change was made, maybe reverting to the previous behavior but having something similar knockout's fooBubble bindings would be a sufficient solution. http://knockoutjs.com/documentation/event-binding.html e.g. `data-keydownBubble="false"`.

**Comment by rniemeyer** [comment]
There is a new option in `0.5.0` to allow bubbling to continue by adding an additional binding like:

```html
<div data-bind="delegatedHandler: 'click', delegatedClickBubble: true"></div>
```

Then, on a case-by-case basis, the handler could even access the event arg and decide to prevent bubbling, if necessary.
